services:
  cdc:
    image: flink:1.20.0-scala_2.12
    hostname: cdc
    container_name: cdc
    networks:
      canal:
    environment:
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-presto-1.20.0.jar
      - |
        FLINK_PROPERTIES=
        rest.bind-address: 0.0.0.0
        jobmanager.bind-host: 0.0.0.0
        taskmanager.bind-host: 0.0.0.0
        job
        high-availability.type: zookeeper
        high-availability.storageDir: s3://flink/ha
        high-availability.zookeeper.quorum: zoo1:2181
        state.checkpoints.dir: s3://flink-state/flink-checkpoints
        state.savepoints.dir: s3://flink-state/flink-savepoints
        s3.endpoint: http://192.168.56.200:9000
        s3.path.style.access: true
        s3.access-key: u5SybesIDVX9b6Pk
        s3.secret-key: lOpH1v7kdM6H8NkPu1H2R6gLc9jcsmWM        
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9091
    volumes:
      # - /etc/localtime:/etc/localtime
      - .:/data
    command: taskmanager
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #       tail -f /dev/null

networks:
  canal:
    external: true