services:
  jobmanager:
    image: flink:1.20.0-scala_2.12
    container_name: jobmanager
    environment:
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-presto-1.20.0.jar
      - |
        FLINK_PROPERTIES=
        state.backend.type: rocksdb
        execution.checkpointing.interval: 3000
        rest.bind-address: 0.0.0.0
        rest.address: jobmanager
        jobmanager.bind-host: 0.0.0.0
        taskmanager.bind-host: 0.0.0.0
        high-availability.type: zookeeper
        high-availability.storageDir: s3://flink/ha
        high-availability.zookeeper.quorum: zoo1:2181
        execution.checkpointing.dir: s3://flink-state/flink-checkpoints
        execution.checkpointing.savepoint-dir: s3://flink-state/flink-savepoints
        s3.endpoint: http://192.168.56.200:9000
        s3.path.style.access: true
        s3.access-key: u5SybesIDVX9b6Pk
        s3.secret-key: lOpH1v7kdM6H8NkPu1H2R6gLc9jcsmWM
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9091
    ports:
      - "48081:8081"
    command: jobmanager
    # volumes:
    #   - ./jars/flink-sql-connector-mysql-cdc-2.4.1.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.4.1.jar
    #   - ./jars/flink-connector-jdbc-3.1.0-1.17.jar:/opt/flink/lib/flink-connector-jdbc-3.1.0-1.17.jar
    #   - ./jars/flink-connector-redis-1.3.0-jar-with-dependencies.jar:/opt/flink/lib/flink-connector-redis-1.3.0-jar-with-dependencies.jar
    #   - ./jobs/job.sql:/opt/flink/job.sql
    networks:
      canal:
  taskmanager:
    image: flink:1.20.0-scala_2.12
    environment:
      - ENABLE_BUILT_IN_PLUGINS=flink-s3-fs-presto-1.20.0.jar
      - |
        FLINK_PROPERTIES=
        state.backend.type: rocksdb
        execution.checkpointing.interval: 3000
        rest.bind-address: 0.0.0.0
        jobmanager.bind-host: 0.0.0.0
        taskmanager.bind-host: 0.0.0.0
        high-availability.type: zookeeper
        high-availability.storageDir: s3://flink/ha
        high-availability.zookeeper.quorum: zoo1:2181
        execution.checkpointing.dir: s3://flink-state/flink-checkpoints
        execution.checkpointing.savepoint-dir: s3://flink-state/flink-savepoints
        s3.endpoint: http://192.168.56.200:9000
        s3.path.style.access: true
        s3.access-key: u5SybesIDVX9b6Pk
        s3.secret-key: lOpH1v7kdM6H8NkPu1H2R6gLc9jcsmWM        
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9091
    depends_on:
      - jobmanager
    command: taskmanager
    # volumes:
    #   - ./jars/flink-sql-connector-mysql-cdc-2.4.1.jar:/opt/flink/lib/flink-sql-connector-mysql-cdc-2.4.1.jar
    #   - ./jars/flink-connector-jdbc-3.1.0-1.17.jar:/opt/flink/lib/flink-connector-jdbc-3.1.0-1.17.jar
    #   - ./jars/flink-connector-redis-1.3.0-jar-with-dependencies.jar:/opt/flink/lib/flink-connector-redis-1.3.0-jar-with-dependencies.jar
    deploy:
      replicas: 2
    networks:
      canal:
networks:
  canal:
    external: true